services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: smartfinanceai_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
  
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    container_name: smartfinanceai_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
  db:
    image: postgres:15
    container_name: smartfinanceai_db
    restart: always
    environment:
      POSTGRES_USER: smartfinance
      POSTGRES_PASSWORD: smartfinance123
      POSTGRES_DB: smartfinanceai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data:  # Definição do volume no nível correto
